In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
from sklearn.tree import export_graphviz
from IPython.display import Image
import pydotplus

import warnings
warnings.filterwarnings('ignore')

In [34]:
import pandas as pd



sana = pd.read_csv("Indian_Employee_Data.csv")

In [3]:
sana.head()

,Employee_ID,Name,Age,Gender,Department,Position,Salary,Experience_Years,City,State,Education,Performance_Rating,Joining_Date,Projects_Completed,Overtime_Hours
0,EMP001,Rajesh Kumar,32.0,Male,Engineering,Senior Developer,850000.0,8.0,Bangalore,Karnataka,B.Tech,4.2,03/15/2016,12.0,45.0
1,EMP002,Priya Sharma,28.0,Female,Marketing,Marketing Manager,720000.0,5.0,Mumbai,Maharashtra,MBA,4.5,01/20/2019,8.0,32.0
2,EMP003,Amit Singh,35.0,Male,Finance,Financial Analyst,650000.0,10.0,Delhi,Delhi,CA,3.8,07/10/2014,15.0,28.0
3,EMP004,Sneha Patel,26.0,Female,NaN,HR Executive,480000.0,3.0,Ahmedabad,Gujarat,MBA,4.1,05/12/2021,6.0,20.0
4,EMP005,Vikram Reddy,40.0,Male,Engineering,Tech Lead,1200000.0,15.0,Hyderabad,Telangana,M.Tech,4.7,11/08/2009,25.0,55.0

In [4]:
sana.tail()

,Employee_ID,Name,Age,Gender,Department,Position,Salary,Experience_Years,City,State,Education,Performance_Rating,Joining_Date,Projects_Completed,Overtime_Hours
44,EMP045,Neha Kapoor,28.0,Female,IT,Data Analyst,NaN,4.0,Bangalore,Karnataka,M.Sc,3.8,04/12/2020,6.0,29.0
45,EMP046,Amit Sharma,27.0,Male,IT,Junior Developer,650000.0,4.0,Delhi,NaN,B.Tech,4.5,08/20/2020,5.0,25.0
46,EMP047,Riya Gupta,32.0,Female,HR,HR Specialist,NaN,8.0,Mumbai,Maharashtra,MBA,NaN,11/03/2016,inf,42.0
47,EMP048,Rohit Bansal,36.0,Male,Finance,Senior Analyst,980000.0,12.0,Mumbai,Maharashtra,CA,4.9,03/20/2012,19.0,51.0
48,EMP049,Sneha Tiwari,25.0,Female,Sales,Sales Representative,inf,2.0,Kolkata,West Bengal,B.Com,3.6,05/14/2022,3.0,16.0

In [5]:
sana.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         49 non-null     object
 1   Name                49 non-null     object
 2   Age                 47 non-null     float64
 3   Gender              49 non-null     object
 4   Department          48 non-null     object
 5   Position            48 non-null     object
 6   Salary              44 non-null     float64
 7   Experience_Years    47 non-null     float64
 8   City                49 non-null     object
 9   State               46 non-null     object
 10  Education           49 non-null     object
 11  Performance_Rating  45 non-null     float64
 12  Joining_Date        48 non-null     object
 13  Projects_Completed  48 non-null     float64
 14  Overtime_Hours      48 non-null     float64
dtypes: float64(6), object(9)
memory usage: 5.9+ KB

In [6]:
sana.shape

(49, 15)

In [13]:
sana.dtypes

Employee_ID            object
Name                   object
Age                   float64
Gender                 object
Department             object
Position               object
Salary                float64
Experience_Years      float64
City                   object
State                  object
Education              object
Performance_Rating    float64
Joining_Date           object
Projects_Completed    float64
Overtime_Hours        float64
dtype: object

In [27]:
sana.isnull()

,Employee_ID,Name,Age,Gender,Department,Position,Salary,Experience_Years,City,State,Education,Performance_Rating,Joining_Date,Projects_Completed,Overtime_Hours
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
31,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
37,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [11]:
sana.isnull().sum()

Employee_ID           0
Name                  0
Age                   2
Gender                0
Department            1
Position              1
Salary                5
Experience_Years      2
City                  0
State                 3
Education             0
Performance_Rating    4
Joining_Date          1
Projects_Completed    1
Overtime_Hours        1
dtype: int64

In [35]:
sana['Department'].fillna(sana['Department'].mode()[0],inplace=True)

In [36]:
sana['Position'].fillna(sana['Position'].mode()[0],inplace=True)

In [37]:
sana['Performance_Rating'].fillna(sana['Performance_Rating'].mean(),inplace=True)

In [38]:
sana['Overtime_Hours'].fillna(sana['Overtime_Hours'].mode()[0],inplace=True)

In [39]:
sana.isnull().sum()

Employee_ID           0
Name                  0
Age                   2
Gender                0
Department            0
Position              0
Salary                5
Experience_Years      2
City                  0
State                 3
Education             0
Performance_Rating    0
Joining_Date          1
Projects_Completed    1
Overtime_Hours        0
dtype: int64

In [52]:
sana['Monthly Salary'].fillna(sana['Monthly Salary'].mean(), inplace=True)

In [53]:
sana.drop_duplicates()

,Employee_ID,Name,Age,Gender,Department,Position,Monthly Salary,Experience_Years,City,State,Education,Performance_Rating,Joining_Date,Projects_Completed,Overtime_Hours
0,EMP001,Rajesh Kumar,32.000000,Male,Engineering,Senior Developer,850000.0,8.0,Bangalore,Karnataka,B.Tech,4.200000,03/15/2016,12.0,45.0
1,EMP002,Priya Sharma,28.000000,Female,Marketing,Marketing Manager,720000.0,5.0,Mumbai,Maharashtra,MBA,4.500000,01/20/2019,8.0,32.0
2,EMP003,Amit Singh,35.000000,Male,Finance,Financial Analyst,650000.0,10.0,Delhi,Delhi,CA,3.800000,07/10/2014,15.0,28.0
3,EMP004,Sneha Patel,26.000000,Female,IT,HR Executive,480000.0,3.0,Ahmedabad,Gujarat,MBA,4.100000,05/12/2021,6.0,20.0
4,EMP005,Vikram Reddy,40.000000,Male,Engineering,Tech Lead,1200000.0,15.0,Hyderabad,Telangana,M.Tech,4.700000,11/08/2009,25.0,55.0
5,EMP006,Kavya Nair,29.000000,Female,Sales,Sales Executive,550000.0,4.0,Chennai,Tamil Nadu,B.Com,3.900000,02/28/2020,inf,38.0
6,EMP007,Arjun Gupta,31.000000,Male,Engineering,DevOps Engineer,inf,7.0,Pune,Maharashtra,B.Tech,4.300000,09/14/2017,11.0,42.0
7,EMP008,Meera Joshi,27.000000,Female,Design,UI/UX Designer,620000.0,4.0,Bangalore,Karnataka,B.Des,4.400000,08/03/2020,7.0,25.0
8,EMP009,Rohit Agarwal,33.000000,Male,Finance,Data Analyst,580000.0,9.0,Kolkata,West Bengal,M.Com,3.700000,12/01/2015,13.0,30.0
9,EMP010,Anita Verma,38.000000,Female,HR,HR Manager,950000.0,12.0,Gurgaon,Haryana,MBA,4.600000,04/18/2012,18.0,48.0
10,EMP011,Suresh Iyer,42.000000,Male,Engineering,Principal Engineer,1350000.0,18.0,Chennai,Tamil Nadu,M.Tech,4.800000,01/25/2006,30.0,60.0
11,EMP012,Pooja Malhotra,32.914894,Female,Marketing,Digital Marketing Specialist,450000.0,2.0,Delhi,Delhi,BBA,4.000000,03/10/2022,4.0,15.0
12,EMP013,Karan Chopra,30.000000,Male,Sales,Sales Manager,780000.0,6.0,Mumbai,Maharashtra,MBA,4.200000,06/22/2018,10.0,35.0
13,EMP014,Divya Rao,34.000000,Female,Engineering,Data Scientist,950000.0,8.0,Bangalore,Karnataka,M.Sc,4.500000,10/05/2016,14.0,40.0
14,EMP015,Manoj Tiwari,36.000000,Male,Operations,Operations Manager,820000.0,inf,Noida,Uttar Pradesh,B.Tech,4.100000,08/30/2013,16.0,45.0
15,EMP016,Ritu Bansal,28.000000,Female,Finance,Financial Planner,580000.0,5.0,Jaipur,NaN,MBA,3.900000,11/15/2019,8.0,22.0
16,EMP017,Deepak Kumar,39.000000,Male,Engineering,Software Architect,1150000.0,14.0,Hyderabad,Telangana,M.Tech,4.600000,02/12/2010,inf,52.0
17,EMP018,Sonia Kapoor,26.000000,Female,Design,Graphic Designer,420000.0,3.0,Chandigarh,Punjab,B.Des,4.000000,07/08/2021,5.0,18.0
18,EMP019,Rahul Saxena,32.000000,Male,Marketing,Product Manager,890000.0,7.0,Pune,Maharashtra,MBA,4.295556,04/20/2017,12.0,38.0
19,EMP020,Nisha Pandey,29.000000,Female,HR,Talent Acquisition Specialist,520000.0,4.0,Lucknow,Uttar Pradesh,MBA,4.200000,09/25/2020,7.0,28.0
20,EMP021,Gaurav Mishra,37.000000,Male,Engineering,Full Stack Developer,820000.0,10.0,Indore,Madhya Pradesh,B.Tech,4.300000,05/16/2014,17.0,44.0
21,EMP022,Preeti Singh,31.000000,Female,Sales,Regional Sales Head,950000.0,inf,Bhopal,Madhya Pradesh,MBA,4.500000,12/03/2016,13.0,46.0
22,EMP023,Ashish Jain,28.000000,Male,Finance,Investment Analyst,680000.0,5.0,Surat,Gujarat,CFA,4.100000,08/14/2019,9.0,33.0
23,EMP024,Swati Agrawal,33.000000,Female,Operations,Process Manager,720000.0,9.0,Nagpur,Maharashtra,B.Tech,4.000000,03/28/2015,14.0,36.0
24,EMP025,Vishal Gupta,35.000000,Male,Engineering,Machine Learning Engineer,1050000.0,9.0,Bangalore,Karnataka,M.Tech,4.700000,09/10/2015,16.0,48.0
25,EMP026,Arjun Pandey,32.914894,Male,IT,Software Engineer,750000.0,7.0,Jaipur,Rajasthan,B.Tech,4.400000,06/15/2017,11.0,37.0
26,EMP027,Neha Kapoor,28.000000,Female,IT,Data Analyst,inf,4.0,Bangalore,Karnataka,M.Sc,3.800000,04/12/2020,6.0,29.0
27,EMP028,Amit Sharma,27.000000,Male,IT,Junior Developer,650000.0,4.0,Delhi,NaN,B.Tech,4.500000,08/20/2020,5.0,25.0
28,EMP029,Riya Gupta,32.000000,Female,HR,HR Specialist,inf,8.0,Mumbai,Maharashtra,MBA,3.800000,11/03/2016,12.0,42.0
29,EMP030,Rajesh Verma,45.000000,Male,Finance,CFO,1200000.0,inf,Bangalore,Karnataka,CA,4.900000,02/28/2005,28.0,65.0
30,EMP031,Priya Singh,29.000000,Female,IT,QA Engineer,720000.0,6.0,Kolkata,West Bengal,B.Tech,4.200000,09/14/2018,inf,33.0
31,EMP032,Sunil Kumar,26.000000,Male,Sales,Sales Executive,500000.0,3.0,Chennai,Tamil Nadu,B.Com,4.295556,01/10/2021,4.0,22.0
32,EMP033,Alok Mehta,52.000000,Male,Operations,VP Operations,2000000.0,28.0,Hyderabad,Telangana,MBA,5.000000,05/18/1996,45.0,inf
33,EMP034,Kavita Yadav,31.000000,Female,IT,DevOps Engineer,inf,10.0,Pune,Maharashtra,B.Tech,4.000000,12/07/2014,15.0,44.0
34,EMP035,Pankaj Mishra,24.000000,Male,Marketing,Marketing Associate,-45000.0,2.0,Jaipur,Rajasthan,BBA,3.500000,07/25/2022,3.0,18.0
35,EMP036,Deepika Roy,48.000000,Female,Management,Director,3000000.0,30.0,Bangalore,Karnataka,MBA,5.000000,03/12/1994,50.0,72.0
36,EMP037,Ramesh Patel,29.000000,Male,IT,Backend Developer,720000.0,6.0,Kolkata,West Bengal,B.Tech,4.200000,NaN,9.0,35.0
37,EMP038,Meera Nair,34.000000,Female,HR,Senior HR Manager,820000.0,9.0,Kochi,Kerala,MBA,4.300000,08/19/2015,14.0,25.0
38,EMP039,Sameer Desai,37.000000,Male,Finance,Finance Manager,1100000.0,15.0,Delhi,Delhi,CA,4.800000,10/05/2009,22.0,58.0
39,EMP040,Swati Joshi,29.000000,Female,IT,Full Stack Developer,650000.0,5.0,Mumbai,Maharashtra,B.Tech,4.295556,04/30/2019,8.0,31.0
40,EMP041,Vinod Iyer,55.000000,Male,Management,CEO,5000000.0,35.0,Chennai,Tamil Nadu,MBA,5.000000,01/15/1989,inf,80.0
41,EMP042,Anjali Saxena,23.000000,Female,HR,HR Trainee,380000.0,3.0,Pune,Maharashtra,MBA,3.900000,11/22/2021,2.0,12.0
42,EMP043,Manish Khanna,40.000000,Male,Operations,Operations Head,1250000.0,18.0,Hyderabad,Telangana,B.Tech,4.700000,07/08/2006,32.0,62.0
43,EMP044,Arjun Pandey,31.000000,Male,IT,Software Engineer,750000.0,7.0,Jaipur,Rajasthan,B.Tech,4.400000,06/15/2017,11.0,37.0
44,EMP045,Neha Kapoor,28.000000,Female,IT,Data Analyst,inf,4.0,Bangalore,Karnataka,M.Sc,3.800000,04/12/2020,6.0,29.0
45,EMP046,Amit Sharma,27.000000,Male,IT,Junior Developer,650000.0,4.0,Delhi,NaN,B.Tech,4.500000,08/20/2020,5.0,25.0
46,EMP047,Riya Gupta,32.000000,Female,HR,HR Specialist,inf,8.0,Mumbai,Maharashtra,MBA,4.295556,11/03/2016,inf,42.0
47,EMP048,Rohit Bansal,36.000000,Male,Finance,Senior Analyst,980000.0,12.0,Mumbai,Maharashtra,CA,4.900000,03/20/2012,19.0,51.0
48,EMP049,Sneha Tiwari,25.000000,Female,Sales,Sales Representative,inf,2.0,Kolkata,West Bengal,B.Com,3.600000,05/14/2022,3.0,16.0

In [54]:
sana.rename(columns = {"Salary":"Monthly Salary"},inplace=True)
sana.fillna(sana.mean(numeric_only=True),inplace=True)

In [55]:
sana.head()

,Employee_ID,Name,Age,Gender,Department,Position,Monthly Salary,Experience_Years,City,State,Education,Performance_Rating,Joining_Date,Projects_Completed,Overtime_Hours
0,EMP001,Rajesh Kumar,32.0,Male,Engineering,Senior Developer,850000.0,8.0,Bangalore,Karnataka,B.Tech,4.2,03/15/2016,12.0,45.0
1,EMP002,Priya Sharma,28.0,Female,Marketing,Marketing Manager,720000.0,5.0,Mumbai,Maharashtra,MBA,4.5,01/20/2019,8.0,32.0
2,EMP003,Amit Singh,35.0,Male,Finance,Financial Analyst,650000.0,10.0,Delhi,Delhi,CA,3.8,07/10/2014,15.0,28.0
3,EMP004,Sneha Patel,26.0,Female,IT,HR Executive,480000.0,3.0,Ahmedabad,Gujarat,MBA,4.1,05/12/2021,6.0,20.0
4,EMP005,Vikram Reddy,40.0,Male,Engineering,Tech Lead,1200000.0,15.0,Hyderabad,Telangana,M.Tech,4.7,11/08/2009,25.0,55.0

In [56]:
sana.fillna(sana.mean(numeric_only=True),inplace=True)

In [59]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Replace infinity values with NaN
sana["Monthly Salary"].replace([np.inf, -np.inf], np.nan, inplace=True)

# Fill missing values using Mean
sana["Monthly Salary"].fillna(
    sana["Monthly Salary"].mean(),
    inplace=True
)

# OR, if sir asked to use Mode instead of Mean, use this:
# sana["Monthly Salary"].fillna(
#     sana["Monthly Salary"].mode()[0],
#     inplace=True
# )

# Create scaler object
scaler = StandardScaler()

# Apply Standard Scaling
sana["Monthly Salary"] = scaler.fit_transform(
    sana[["Monthly Salary"]]
)

# Display the DataFrame
print(sana)

ValueError: Input X contains infinity or a value too large for dtype('float64').

In [60]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# Fill null values using mean
sana.fillna(sana.mean(numeric_only=True), inplace=True)

# Replace infinity values with NaN (if any)
sana.replace([np.inf, -np.inf], np.nan, inplace=True)

# Again fill any new NaN values created above
sana.fillna(sana.mean(numeric_only=True), inplace=True)

# Standard Scaling
scaler = StandardScaler()
sana["Monthly Salary"] = scaler.fit_transform(sana[["Monthly Salary"]])

print(sana)

   Employee_ID            Name        Age  Gender   Department  \
0       EMP001    Rajesh Kumar  32.000000    Male  Engineering
1       EMP002    Priya Sharma  28.000000  Female    Marketing
2       EMP003      Amit Singh  35.000000    Male      Finance
3       EMP004     Sneha Patel  26.000000  Female           IT
4       EMP005    Vikram Reddy  40.000000    Male  Engineering
5       EMP006      Kavya Nair  29.000000  Female        Sales
6       EMP007     Arjun Gupta  31.000000    Male  Engineering
7       EMP008     Meera Joshi  27.000000  Female       Design
8       EMP009   Rohit Agarwal  33.000000    Male      Finance
9       EMP010     Anita Verma  38.000000  Female           HR
10      EMP011     Suresh Iyer  42.000000    Male  Engineering
11      EMP012  Pooja Malhotra  32.914894  Female    Marketing
12      EMP013    Karan Chopra  30.000000    Male        Sales
13      EMP014       Divya Rao  34.000000  Female  Engineering
14      EMP015    Manoj Tiwari  36.000000    Male   Operations
15      EMP016     Ritu Bansal  28.000000  Female      Finance
16      EMP017    Deepak Kumar  39.000000    Male  Engineering
17      EMP018    Sonia Kapoor  26.000000  Female       Design
18      EMP019    Rahul Saxena  32.000000    Male    Marketing
19      EMP020    Nisha Pandey  29.000000  Female           HR
20      EMP021   Gaurav Mishra  37.000000    Male  Engineering
21      EMP022    Preeti Singh  31.000000  Female        Sales
22      EMP023     Ashish Jain  28.000000    Male      Finance
23      EMP024   Swati Agrawal  33.000000  Female   Operations
24      EMP025    Vishal Gupta  35.000000    Male  Engineering
25      EMP026    Arjun Pandey  32.914894    Male           IT
26      EMP027     Neha Kapoor  28.000000  Female           IT
27      EMP028     Amit Sharma  27.000000    Male           IT
28      EMP029      Riya Gupta  32.000000  Female           HR
29      EMP030    Rajesh Verma  45.000000    Male      Finance
30      EMP031     Priya Singh  29.000000  Female           IT
31      EMP032     Sunil Kumar  26.000000    Male        Sales
32      EMP033      Alok Mehta  52.000000    Male   Operations
33      EMP034    Kavita Yadav  31.000000  Female           IT
34      EMP035   Pankaj Mishra  24.000000    Male    Marketing
35      EMP036     Deepika Roy  48.000000  Female   Management
36      EMP037    Ramesh Patel  29.000000    Male           IT
37      EMP038      Meera Nair  34.000000  Female           HR
38      EMP039    Sameer Desai  37.000000    Male      Finance
39      EMP040     Swati Joshi  29.000000  Female           IT
40      EMP041      Vinod Iyer  55.000000    Male   Management
41      EMP042   Anjali Saxena  23.000000  Female           HR
42      EMP043   Manish Khanna  40.000000    Male   Operations
43      EMP044    Arjun Pandey  31.000000    Male           IT
44      EMP045     Neha Kapoor  28.000000  Female           IT
45      EMP046     Amit Sharma  27.000000    Male           IT
46      EMP047      Riya Gupta  32.000000  Female           HR
47      EMP048    Rohit Bansal  36.000000    Male      Finance
48      EMP049    Sneha Tiwari  25.000000  Female        Sales

                         Position  Monthly Salary  Experience_Years  \
0                Senior Developer   -1.342531e-01          8.000000
1               Marketing Manager   -3.128211e-01          5.000000
2               Financial Analyst   -4.089731e-01         10.000000
3                    HR Executive   -6.424851e-01          3.000000
4                       Tech Lead    3.465070e-01         15.000000
5                 Sales Executive   -5.463331e-01          4.000000
6                 DevOps Engineer    1.599081e-16          7.000000
7                  UI/UX Designer   -4.501811e-01          4.000000
8                    Data Analyst   -5.051251e-01          9.000000
9                      HR Manager    3.106953e-03         12.000000
10             Principal Engineer    5.525470e-01         18.000000
11   Digital Marketing Specialist   -6.836931e-01          2.000000
12                  Sales Manager   -2.304051e-01          6.000000
13                 Data Scientist    3.106953e-03          8.000000
14             Operations Manager   -1.754611e-01          8.847826
15              Financial Planner   -5.051251e-01          5.000000
16             Software Architect    2.778270e-01         14.000000
17               Graphic Designer   -7.249011e-01          3.000000
18                Product Manager   -7.930905e-02          7.000000
19  Talent Acquisition Specialist   -5.875411e-01          4.000000
20           Full Stack Developer   -1.754611e-01         10.000000
21            Regional Sales Head    3.106953e-03          8.847826
22             Investment Analyst   -3.677651e-01          5.000000
23                Process Manager   -3.128211e-01          9.000000
24      Machine Learning Engineer    1.404670e-01          9.000000
25              Software Engineer   -2.716131e-01          7.000000
26                   Data Analyst    1.599081e-16          4.000000
27               Junior Developer   -4.089731e-01          4.000000
28                  HR Specialist    1.599081e-16          8.000000
29                            CFO    3.465070e-01          8.847826
30                    QA Engineer   -3.128211e-01          6.000000
31                Sales Executive   -6.150131e-01          3.000000
32                  VP Operations    1.445387e+00         28.000000
33                DevOps Engineer    1.599081e-16         10.000000
34            Marketing Associate   -1.363625e+00          2.000000
35                       Director    2.818987e+00         30.000000
36              Backend Developer   -3.128211e-01          6.000000
37              Senior HR Manager   -1.754611e-01          9.000000
38                Finance Manager    2.091470e-01         15.000000
39           Full Stack Developer   -4.089731e-01          5.000000
40                            CEO    5.566187e+00         35.000000
41                     HR Trainee   -7.798451e-01          3.000000
42                Operations Head    4.151870e-01         18.000000
43              Software Engineer   -2.716131e-01          7.000000
44                   Data Analyst    1.599081e-16          4.000000
45               Junior Developer   -4.089731e-01          4.000000
46                  HR Specialist    1.599081e-16          8.000000
47                 Senior Analyst    4.431496e-02         12.000000
48           Sales Representative    1.599081e-16          2.000000

          City           State Education  Performance_Rating Joining_Date  \
0    Bangalore       Karnataka    B.Tech            4.200000   03/15/2016
1       Mumbai     Maharashtra       MBA            4.500000   01/20/2019
2        Delhi           Delhi        CA            3.800000   07/10/2014
3    Ahmedabad         Gujarat       MBA            4.100000   05/12/2021
4    Hyderabad       Telangana    M.Tech            4.700000   11/08/2009
5      Chennai      Tamil Nadu     B.Com            3.900000   02/28/2020
6         Pune     Maharashtra    B.Tech            4.300000   09/14/2017
7    Bangalore       Karnataka     B.Des            4.400000   08/03/2020
8      Kolkata     West Bengal     M.Com            3.700000   12/01/2015
9      Gurgaon         Haryana       MBA            4.600000   04/18/2012
10     Chennai      Tamil Nadu    M.Tech            4.800000   01/25/2006
11       Delhi           Delhi       BBA            4.000000   03/10/2022
12      Mumbai     Maharashtra       MBA            4.200000   06/22/2018
13   Bangalore       Karnataka      M.Sc            4.500000   10/05/2016
14       Noida   Uttar Pradesh    B.Tech            4.100000   08/30/2013
15      Jaipur             NaN       MBA            3.900000   11/15/2019
16   Hyderabad       Telangana    M.Tech            4.600000   02/12/2010
17  Chandigarh          Punjab     B.Des            4.000000   07/08/2021
18        Pune     Maharashtra       MBA            4.295556   04/20/2017
19     Lucknow   Uttar Pradesh       MBA            4.200000   09/25/2020
20      Indore  Madhya Pradesh    B.Tech            4.300000   05/16/2014
21      Bhopal  Madhya Pradesh       MBA            4.500000   12/03/2016
22       Surat         Gujarat       CFA            4.100000   08/14/2019
23      Nagpur     Maharashtra    B.Tech            4.000000   03/28/2015
24   Bangalore       Karnataka    M.Tech            4.700000   09/10/2015
25      Jaipur       Rajasthan    B.Tech            4.400000   06/15/2017
26   Bangalore       Karnataka      M.Sc            3.800000   04/12/2020
27       Delhi             NaN    B.Tech            4.500000   08/20/2020
28      Mumbai     Maharashtra       MBA            3.800000   11/03/2016
29   Bangalore       Karnataka        CA            4.900000   02/28/2005
30     Kolkata     West Bengal    B.Tech            4.200000   09/14/2018
31     Chennai      Tamil Nadu     B.Com            4.295556   01/10/2021
32   Hyderabad       Telangana       MBA            5.000000   05/18/1996
33        Pune     Maharashtra    B.Tech            4.000000   12/07/2014
34      Jaipur       Rajasthan       BBA            3.500000   07/25/2022
35   Bangalore       Karnataka       MBA            5.000000   03/12/1994
36     Kolkata     West Bengal    B.Tech            4.200000          NaN
37       Kochi          Kerala       MBA            4.300000   08/19/2015
38       Delhi           Delhi        CA            4.800000   10/05/2009
39      Mumbai     Maharashtra    B.Tech            4.295556   04/30/2019
40     Chennai      Tamil Nadu       MBA            5.000000   01/15/1989
41        Pune     Maharashtra       MBA            3.900000   11/22/2021
42   Hyderabad       Telangana    B.Tech            4.700000   07/08/2006
43      Jaipur       Rajasthan    B.Tech            4.400000   06/15/2017
44   Bangalore       Karnataka      M.Sc            3.800000   04/12/2020
45       Delhi             NaN    B.Tech            4.500000   08/20/2020
46      Mumbai     Maharashtra       MBA            4.295556   11/03/2016
47      Mumbai     Maharashtra        CA            4.900000   03/20/2012
48     Kolkata     West Bengal     B.Com            3.600000   05/14/2022

    Projects_Completed  Overtime_Hours
0            12.000000       45.000000
1             8.000000       32.000000
2            15.000000       28.000000
3             6.000000       20.000000
4            25.000000       55.000000
5            13.636364       38.000000
6            11.000000       42.000000
7             7.000000       25.000000
8            13.000000       30.000000
9            18.000000       48.000000
10           30.000000       60.000000
11            4.000000       15.000000
12           10.000000       35.000000
13           14.000000       40.000000
14           16.000000       45.000000
15            8.000000       22.000000
16           13.636364       52.000000
17            5.000000       18.000000
18           12.000000       38.000000
19            7.000000       28.000000
20           17.000000       44.000000
21           13.000000       46.000000
22            9.000000       33.000000
23           14.000000       36.000000
24           16.000000       48.000000
25           11.000000       37.000000
26            6.000000       29.000000
27            5.000000       25.000000
28           12.000000       42.000000
29           28.000000       65.000000
30           13.636364       33.000000
31            4.000000       22.000000
32           45.000000       37.770833
33           15.000000       44.000000
34            3.000000       18.000000
35           50.000000       72.000000
36            9.000000       35.000000
37           14.000000       25.000000
38           22.000000       58.000000
39            8.000000       31.000000
40           13.636364       80.000000
41            2.000000       12.000000
42           32.000000       62.000000
43           11.000000       37.000000
44            6.000000       29.000000
45            5.000000       25.000000
46           13.636364       42.000000
47           19.000000       51.000000
48            3.000000       16.000000